name: ai_tools
description: "Build AI tools with flutter and rust(candle)"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  animated_toggle_switch: ^0.8.3
  desktop_drop: ^0.5.0
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  flutter_riverpod: ^2.5.1
  flutter_rust_bridge: 2.5.1
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+6
  path_provider: ^2.1.5
  riverpod: ^2.5.1
  rust_lib_ai_tools:
    path: rust_builder
  syncfusion_flutter_charts: ^27.1.58
  toastification: ^2.3.0
  

dev_dependencies:
  build_runner: ^2.4.13 # dart run build_runner build
  flutter_launcher_icons: ^0.14.1 # dart run flutter_launcher_icons
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_generator: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

