name: ai_tools
description: "Build AI tools with flutter and rust(candle)"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_rust_bridge: 2.2.0
  file_selector: ^1.0.3
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+6
  riverpod: ^2.5.1
  rust_lib_ai_tools:
    path: rust_builder
  toastification: ^2.3.0
  

dev_dependencies:
  build_runner: ^2.4.13 # dart run build_runner build
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

