// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ChatResponse {
  final String content;
  final bool done;
  final String stage;
  final String uuid;

  const ChatResponse({
    required this.content,
    required this.done,
    required this.stage,
    required this.uuid,
  });

  @override
  int get hashCode =>
      content.hashCode ^ done.hashCode ^ stage.hashCode ^ uuid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatResponse &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          done == other.done &&
          stage == other.stage &&
          uuid == other.uuid;
}
