// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TrainMessage {
  final String modelName;
  final String message;
  final BigInt epoch;
  final double loss;

  const TrainMessage({
    required this.modelName,
    required this.message,
    required this.epoch,
    required this.loss,
  });

  @override
  int get hashCode =>
      modelName.hashCode ^ message.hashCode ^ epoch.hashCode ^ loss.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrainMessage &&
          runtimeType == other.runtimeType &&
          modelName == other.modelName &&
          message == other.message &&
          epoch == other.epoch &&
          loss == other.loss;
}
