// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> runServer({BigInt? port}) =>
    RustLib.instance.api.crateApiWebServerRunServer(port: port);

Future<void> loadLlmModel({required String modelPath}) =>
    RustLib.instance.api.crateApiWebServerLoadLlmModel(modelPath: modelPath);

Future<void> stopServer() => RustLib.instance.api.crateApiWebServerStopServer();

bool checkModalStatus() =>
    RustLib.instance.api.crateApiWebServerCheckModalStatus();
